### ISSUE TITLE
TypeformData::UnexpectedError on responses from "Duplicated" typeforms

### ISSUE THREAD

**Issue by robcole** [shearwaterintl/typeform_data#12] opened 2017-03-09 06:04 UTC
Hey guys,

Great work on the gem. I was building something similar and researching approaches for dealing with some of their formatting (specifically the odd way they include answers for multiple choice questions, especially multiple choice questions where they allow you to choose multiple things and/or have an `other` field) when I stumbled across this gem. 

Unfortunately, I've encountered yet-another edge case with Typeform's wonderful data. 
As far as I can tell, here are the steps to duplicate. 

1) Create a form
2) Duplicate it in their UI
3) Answer the form, then try to get that request

```
client = TypeformData::Client.new(api_key: "key")
typeform = client.all_typeforms.first # assum
typeform.responses.first

=> TypeformData::UnexpectedError: Expected to find a matching field
	from /app/user/vendor/gems/typeform_data-3.0.0/lib/typeform_data/typeform/answer.rb:70:in `block (2 levels) in from_response_attrs'
...
```

Here's data from one of our Typeforms that triggers this:

https://gist.github.com/robcole/fdfa95d0bdd1552ef08e877aa5d416b7

I've got quite a few more forms where this happens (happy to share that JSON as well if it helps), and may take a look to see if there's a (hopefully) relatively simple fix for this if you'd be interested in a PR. Let me know if you guys have any immediate thoughts based on the gist above though.

best,
Rob

**Comment by marisawallace** [comment] 2017-03-09 13:16
@robcole thanks for opening this issue! I've got a new branch pushed up at https://github.com/shearwaterintl/typeform_data/tree/failing-testcase-for-issue-12 which contains a failing testcase that replicates the error you're seeing. I was able to reproduce it just by pasting the JSON from your gist into one of our existing tests :)

I can't dig into this right now, but either myself or @erose will post back here if we start working on this (probably sometime in the next few days at the latest).

 In the meantime, you're welcome to send over a PR if you need a fix more urgently.

**Comment by robcole** [comment] 2017-03-09 19:14
Thanks for the quick response! I took a look for a few hours this morning and while I was able to get a quick fix to pass the initial ID selector issue, there's an assumption in your tests that doesn't match Typeform's data, because of "optional" questions (where they just completely leave the answer out of the dataset).

This means that the current JSON tests will work with anything where all questions are answered, but won't work where an optional question is blank.

https://github.com/useed/typeform_data/commit/902ad34c2f54c44d341dd8bf6b1ddd34eca589b2 is what I've authored so far, which works for your old tests and works for the last response in my JSON example (where each field was answered), but not for the first.

Hope this is helpful enough to get started. I've actually realized as I've dug through your gem that it's not quite a fit for our use case (which is a bit more domain-specific), but I'll probably be solving some similar problems in our gem. 

I'm happy to help bring in solutions from our gem as I figure out some more of these ugly edge cases, and please LMK if there's a direction you'd like to take around your existing tests to ensure a fix for this issue - happy to help more if I can!

**Comment by marisawallace** [comment] 2017-03-16 12:34
@robcole I think your solution (checking question IDs) works in general, and the test case failure you saw was due to some data-specific assertions in the test.

I opened a PR with the fix at https://github.com/shearwaterintl/typeform_data/pull/13 , which also includes new tests for the JSON response you posted.

**Comment by robcole** [comment] 2017-03-16 16:12
Thanks for the update @maxkwallace!

**Comment by erose** [comment] 2017-11-14 16:52
Hey @robcole! Since #13 was merged, I'm going to close this issue. Please reopen if you still have a concern.

Just out of curiosity: did you end up writing your own Typeform gem?

**Closed as completed by erose** 2017-11-14 16:52 UTC

**Comment by robcole** [comment] 2017-11-15 20:11
@erose I did, though it serves a pretty different purpose than yours. Will need to be updating it with their newer formats and endpoints soon enough, but for now it's still working quite well for us - basically the goal is to allow a user to abstract a "model-like" question and answer from a form submission.

https://github.com/useed/typed_form is the gem we've rolled up.
